### ISSUE TITLE
Erros monstruosos [referente a exclusões]

### ISSUE THREAD

**Issue by megaday** [Guganr/Shyme#20]
Deixarei aqui o progresso que fiz até momento, estou com alguns problemas na lógica (talvez estou tentando fazer algo facil ser difícil). 

Tentei usar o GET pra passar o id de membro, postagem etc. mas quando eu clico no botão e ele atualiza a página, o `grupo?id=8&excluirmembro=12` continua lá e quando clico para mudar de aba tem um problema de loop infinito. 
O negócio tá ruim, amanha tento terminar. Se alguem tiver disposto a testar também basta clonar esse [repo aqui](https://github.com/megaday/Shyme-1/tree/9c4b999720ba380d609edc121a218d13e35bae20)

**Comment by felipe349** [comment]
Não sei se entendi direito, mas depois de executar a função, tenta usar o `header("Refresh:0"); `. Uma sugestão só, pq n tenho certeza se irá funcionar.

**Comment by megaday** [comment]
Então, acabei descobrindo que um dos problemas era eu ter usado o `header('Refresh:0');`
Outros problemas eram nomes de métodos errados, alguns parâmetros fora de ordem e o `$_GET['id']` do grupo que estava faltando em alguns lugares
